apiVersion: v1
kind: Route
metadata:
  name: microsvcruntime
  namespace: samplepipeline
spec:
  host: microsvcruntime.193-26-203-31.nip.io
  port:
    targetPort: 5555-tcp
  to:
    kind: Service
    name: microsvcruntimesrv
    weight: 100
  wildcardPolicy: None

